name: Commit validation
run-name: ${{github.actions}} triggered validation workflow
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout in progress
        uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile