name: Master branch
run-name: ${{github.actions}} triggered validation workflow
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Hadolint Action
      - uses: hadolint/hadolint-action@v2.0.0
        with: 
          dockerfile: Dockerfile