name: Master branch
run-name: ${{github.actions}} triggered validation workflow
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
     - uses: actions/checkout@v2 
     - uses: hadolint/hadolint-action@v2.0.0
       with:
        dockerfile: Dockerfile